import PDFDocument from "pdfkit";
import { Response } from "express";

// ── Color palette ──────────────────────────────────────────────────────────────
const C = {
  accent:   "#6366f1",
  accentDk: "#4338ca",
  dark:     "#0f172a",
  slate:    "#1e293b",
  border:   "#e2e8f0",
  muted:    "#94a3b8",
  text:     "#1e293b",
  subtext:  "#64748b",
  rowAlt:   "#f8fafc",
  good:     "#059669",
  goodBg:   "#d1fae5",
  warn:     "#d97706",
  warnBg:   "#fef3c7",
  bad:      "#dc2626",
  badBg:    "#fee2e2",
  white:    "#ffffff",
};

// ── Interfaces ─────────────────────────────────────────────────────────────────
export interface GTMReportData {
  workspace: { name: string; domain?: string };
  period:    string;
  stack:     Record<string, { tool: string; label: string }[]>;
  pipeline:  { sourced: number; enriched: number; contacted: number; replied: number; meetings: number; dealsWon: number };
  metrics:   { openRate: number|null; replyRate: number|null; unsubRate: number|null; bounceRate: number|null; meetingRate: number|null; emailsSent: number; totalPipelineValue: number };
  signals:   { event: string; count: number; tier: number }[];
  tools:     { tool: string; label: string; channel: string; status: string; events24h: number; events7d: number; lastEventAt: string|null }[];
}

// ── Layout constants ───────────────────────────────────────────────────────────
const PAGE_W = 595.28;
const PAGE_H = 841.89;
const MARGIN = 50;
const CONTENT_W = PAGE_W - MARGIN * 2;
const HEADER_H = 42;
const FOOTER_H = 30;
const BODY_TOP = MARGIN + HEADER_H + 12;
const BODY_BOT = PAGE_H - MARGIN - FOOTER_H;

// ── Helpers ────────────────────────────────────────────────────────────────────

function statusColor(val: number|null, key: string): { text: string; bg: string } {
  if (val === null) return { text: C.subtext, bg: C.rowAlt };
  const thresholds: Record<string, [number, number, boolean]> = {
    bounceRate:  [2, 5, false],
    unsubRate:   [0.5, 1, false],
    openRate:    [40, 20, true],
    replyRate:   [3, 1, true],
    meetingRate: [10, 5, true],
  };
  const t = thresholds[key];
  if (!t) return { text: C.subtext, bg: C.rowAlt };
  const [good, warn, higher] = t;
  if (higher ? val >= good : val <= good) return { text: C.good, bg: C.goodBg };
  if (higher ? val >= warn : val <= warn) return { text: C.warn, bg: C.warnBg };
  return { text: C.bad, bg: C.badBg };
}

function pagePercent(count: number, total: number): string {
  if (total === 0) return "—";
  return `${Math.round((count / total) * 100)}%`;
}

function fmtNum(n: number): string {
  return n.toLocaleString("en-US");
}

// ── Page header & footer ───────────────────────────────────────────────────────

function drawPageChrome(doc: PDFKit.PDFDocument, title: string, workspace: string, pageNum: number) {
  // Header bar
  doc.rect(MARGIN, MARGIN, CONTENT_W, HEADER_H).fill(C.slate);
  doc.fillColor(C.white).font("Helvetica-Bold").fontSize(9)
     .text(title.toUpperCase(), MARGIN + 14, MARGIN + 14, { width: CONTENT_W * 0.6 });
  doc.fillColor(C.muted).font("Helvetica").fontSize(8)
     .text(workspace, MARGIN + 14, MARGIN + 27, { width: CONTENT_W * 0.6 });
  doc.fillColor(C.muted).font("Helvetica").fontSize(8)
     .text(`Page ${pageNum}`, MARGIN, MARGIN + 14, { width: CONTENT_W - 14, align: "right" });

  // Accent strip on header
  doc.rect(MARGIN, MARGIN, 4, HEADER_H).fill(C.accent);

  // Footer
  doc.rect(MARGIN, PAGE_H - MARGIN - FOOTER_H, CONTENT_W, 1).fill(C.border);
  doc.fillColor(C.muted).font("Helvetica").fontSize(7.5)
     .text(
       `Generated by iqpipe · ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
       MARGIN, PAGE_H - MARGIN - FOOTER_H + 8, { width: CONTENT_W * 0.65 }
     );
  doc.fillColor(C.muted).font("Helvetica").fontSize(7.5)
     .text("iqpipe.com", MARGIN, PAGE_H - MARGIN - FOOTER_H + 8, { width: CONTENT_W - 14, align: "right" });
}

// ── Table renderer ─────────────────────────────────────────────────────────────

interface ColDef { header: string; width: number; align?: "left"|"right"|"center"; }
type RowData = { cells: string[]; bg?: string; textColor?: string; bold?: boolean }[];

function drawTable(
  doc: PDFKit.PDFDocument,
  x: number,
  y: number,
  cols: ColDef[],
  rows: RowData,
  rowH = 22
): number {
  const tableW = cols.reduce((s, c) => s + c.width, 0);

  // Header row
  doc.rect(x, y, tableW, rowH).fill(C.slate);
  let cx = x;
  for (const col of cols) {
    doc.fillColor(C.white).font("Helvetica-Bold").fontSize(8)
       .text(col.header, cx + 6, y + 7, { width: col.width - 10, align: col.align ?? "left" });
    cx += col.width;
  }

  let rowY = y + rowH;

  for (const row of rows) {
    const bg = row.bg ?? (rows.indexOf(row) % 2 === 0 ? C.white : C.rowAlt);
    doc.rect(x, rowY, tableW, rowH).fill(bg);

    cx = x;
    for (let i = 0; i < cols.length; i++) {
      const cell = row.cells[i] ?? "";
      doc
        .fillColor(row.textColor ?? C.text)
        .font(row.bold ? "Helvetica-Bold" : "Helvetica")
        .fontSize(8.5)
        .text(cell, cx + 6, rowY + 6, { width: cols[i].width - 10, align: cols[i].align ?? "left" });
      cx += cols[i].width;
    }
    rowY += rowH;
  }

  // Table border
  doc.rect(x, y, tableW, rowY - y).stroke(C.border);

  // Vertical column dividers
  cx = x;
  for (let i = 0; i < cols.length - 1; i++) {
    cx += cols[i].width;
    doc.moveTo(cx, y).lineTo(cx, rowY).stroke(C.border);
  }

  return rowY; // return bottom Y
}

// ── Section heading ────────────────────────────────────────────────────────────

function drawSectionHeading(doc: PDFKit.PDFDocument, title: string, y: number): number {
  doc.rect(MARGIN, y, 3, 16).fill(C.accent);
  doc.fillColor(C.dark).font("Helvetica-Bold").fontSize(11)
     .text(title, MARGIN + 10, y + 2);
  return y + 24;
}

// ── Metric box (small inline) ──────────────────────────────────────────────────

function drawMetricBoxes(
  doc: PDFKit.PDFDocument,
  y: number,
  items: { label: string; value: string; note?: string; statusKey?: string; rawValue?: number|null }[],
  perRow = 3
): number {
  const boxW = CONTENT_W / perRow - 6;
  const boxH = 56;
  const padH = 8;

  let row = 0;
  let col = 0;

  for (const item of items) {
    const bx = MARGIN + col * (boxW + 8);
    const by = y + row * (boxH + 8);
    const sc = item.statusKey ? statusColor(item.rawValue ?? null, item.statusKey) : null;

    doc.rect(bx, by, boxW, boxH).fill(C.rowAlt).stroke(C.border);

    if (sc) {
      doc.rect(bx, by + boxH - 4, boxW, 4).fill(sc.text);
    }

    doc.fillColor(C.subtext).font("Helvetica").fontSize(7.5)
       .text(item.label.toUpperCase(), bx + padH, by + 9, { width: boxW - padH * 2 });
    doc.fillColor(sc ? sc.text : C.dark).font("Helvetica-Bold").fontSize(16)
       .text(item.value, bx + padH, by + 18, { width: boxW - padH * 2 });
    if (item.note) {
      doc.fillColor(C.muted).font("Helvetica").fontSize(7)
         .text(item.note, bx + padH, by + 37, { width: boxW - padH * 2 });
    }

    col++;
    if (col >= perRow) { col = 0; row++; }
  }

  const totalRows = Math.ceil(items.length / perRow);
  return y + totalRows * (boxH + 8);
}

// ── MAIN EXPORT ────────────────────────────────────────────────────────────────

export async function generateGTMReportPDF(data: GTMReportData, res: Response) {
  const doc = new PDFDocument({
    size: "A4",
    margins: { top: MARGIN, bottom: MARGIN, left: MARGIN, right: MARGIN },
    info: {
      Title:    `GTM Health Report — ${data.workspace.name}`,
      Author:   "iqpipe",
      Subject:  "GTM Observability Report",
      Keywords: "GTM, pipeline, outreach, signals",
    },
    autoFirstPage: false,
  });

  doc.pipe(res);

  let pageNum = 0;

  function newPage(sectionTitle: string) {
    doc.addPage();
    pageNum++;
    drawPageChrome(doc, sectionTitle, data.workspace.name, pageNum);
  }

  // ────────────────────────────────────────────────────────────────────────────
  // COVER PAGE
  // ────────────────────────────────────────────────────────────────────────────
  doc.addPage();
  pageNum++;

  // Top color band
  doc.rect(0, 0, PAGE_W, 280).fill(C.slate);
  doc.rect(0, 0, PAGE_W, 6).fill(C.accent);

  // Logo text
  doc.fillColor(C.accent).font("Helvetica-Bold").fontSize(13)
     .text("iqpipe", MARGIN, 50);

  // Report title
  doc.fillColor(C.white).font("Helvetica-Bold").fontSize(36)
     .text("GTM Health Report", MARGIN, 90, { width: CONTENT_W });

  // Subtitle
  doc.fillColor(C.muted).font("Helvetica").fontSize(13)
     .text("GTM Observability · Pipeline · Outreach Performance · Signal Activity", MARGIN, 145, { width: CONTENT_W });

  // Divider
  doc.rect(MARGIN, 180, 60, 3).fill(C.accent);

  // Meta info
  const metaY = 200;
  doc.fillColor(C.muted).font("Helvetica").fontSize(9).text("WORKSPACE", MARGIN, metaY);
  doc.fillColor(C.white).font("Helvetica-Bold").fontSize(11).text(data.workspace.name, MARGIN, metaY + 12);

  doc.fillColor(C.muted).font("Helvetica").fontSize(9).text("PERIOD", MARGIN + 200, metaY);
  doc.fillColor(C.white).font("Helvetica-Bold").fontSize(11).text(data.period, MARGIN + 200, metaY + 12);

  doc.fillColor(C.muted).font("Helvetica").fontSize(9).text("GENERATED", MARGIN + 380, metaY);
  doc.fillColor(C.white).font("Helvetica-Bold").fontSize(11)
     .text(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), MARGIN + 380, metaY + 12);

  // Summary block below band
  const p = data.pipeline;
  const overallConv = p.sourced > 0 ? ((p.dealsWon / p.sourced) * 100).toFixed(2) : "0.00";

  doc.fillColor(C.dark).font("Helvetica-Bold").fontSize(11)
     .text("EXECUTIVE SUMMARY", MARGIN, 300);
  doc.rect(MARGIN, 315, CONTENT_W, 1).fill(C.border);

  const summaryItems = [
    { label: "Leads Sourced", value: fmtNum(p.sourced) },
    { label: "Enriched",      value: fmtNum(p.enriched) },
    { label: "Contacted",     value: fmtNum(p.contacted) },
    { label: "Replied",       value: fmtNum(p.replied) },
    { label: "Meetings",      value: fmtNum(p.meetings) },
    { label: "Deals Won",     value: fmtNum(p.dealsWon) },
    { label: "Source → Won",  value: `${overallConv}%` },
    { label: "Emails Sent",   value: fmtNum(data.metrics.emailsSent) },
    { label: "Pipeline $",    value: data.metrics.totalPipelineValue > 0 ? `$${fmtNum(data.metrics.totalPipelineValue)}` : "—" },
  ];

  const cellW = CONTENT_W / 3;
  let si = 0;
  for (const item of summaryItems) {
    const sc = si % 3;
    const sr = Math.floor(si / 3);
    const sx = MARGIN + sc * cellW;
    const sy = 325 + sr * 55;
    doc.fillColor(C.subtext).font("Helvetica").fontSize(8).text(item.label, sx, sy);
    doc.fillColor(C.dark).font("Helvetica-Bold").fontSize(20).text(item.value, sx, sy + 10);
    si++;
  }

  // Footer on cover
  doc.rect(MARGIN, PAGE_H - MARGIN - 20, CONTENT_W, 1).fill(C.border);
  doc.fillColor(C.muted).font("Helvetica").fontSize(7.5)
     .text("Confidential — generated by iqpipe GTM Observability Platform", MARGIN, PAGE_H - MARGIN - 12);

  // ────────────────────────────────────────────────────────────────────────────
  // PAGE 2: THE STACK
  // ────────────────────────────────────────────────────────────────────────────
  newPage("The Stack");

  let y = BODY_TOP;
  y = drawSectionHeading(doc, "Connected Tools by Category", y);
  y += 8;

  const CATEGORY_LABELS: Record<string, string> = {
    aggregation: "Aggregation", enrichment: "Enrichment", activation: "Activation",
    crm: "CRM", billing: "Billing", infrastructure: "Infrastructure",
  };

  const stackRows: RowData = [];
  for (const [cat, tools] of Object.entries(data.stack)) {
    if (tools.length === 0) continue;
    stackRows.push({
      cells: [CATEGORY_LABELS[cat] ?? cat, tools.map((t) => t.label).join(", "), String(tools.length)],
      bold: false,
    });
  }

  if (stackRows.length === 0) {
    doc.fillColor(C.muted).font("Helvetica").fontSize(9).text("No tools connected.", MARGIN, y);
    y += 20;
  } else {
    y = drawTable(doc, MARGIN, y, [
      { header: "Category",     width: 130 },
      { header: "Tools",        width: 330 },
      { header: "Count",        width: 35, align: "right" },
    ], stackRows) + 20;
  }

  // ────────────────────────────────────────────────────────────────────────────
  // PAGE 3: PIPELINE ANALYSIS
  // ────────────────────────────────────────────────────────────────────────────
  newPage("Pipeline Analysis");

  y = BODY_TOP;
  y = drawSectionHeading(doc, "Funnel Conversion", y);
  y += 8;

  const stages = [
    { label: "Sourced",   count: p.sourced,   prev: p.sourced },
    { label: "Enriched",  count: p.enriched,  prev: p.sourced },
    { label: "Contacted", count: p.contacted, prev: p.sourced },
    { label: "Replied",   count: p.replied,   prev: p.contacted },
    { label: "Meeting",   count: p.meetings,  prev: p.replied },
    { label: "Won",       count: p.dealsWon,  prev: p.meetings },
  ];

  const pipelineRows: RowData = stages.map((s, i) => ({
    cells: [
      s.label,
      fmtNum(s.count),
      pagePercent(s.count, p.sourced),
      i === 0 ? "—" : pagePercent(s.count, s.prev),
      i === 0 ? "—" : fmtNum(s.prev - s.count) + " dropped",
    ],
    bold: s.label === "Won",
    bg: s.label === "Won" ? C.goodBg : undefined,
    textColor: s.label === "Won" ? C.good : undefined,
  }));

  y = drawTable(doc, MARGIN, y, [
    { header: "Stage",          width: 100 },
    { header: "Count",          width: 90,  align: "right" },
    { header: "% of Sourced",   width: 90,  align: "right" },
    { header: "Stage Conv.",    width: 90,  align: "right" },
    { header: "Drop-off",       width: 125, align: "right" },
  ], pipelineRows) + 20;

  // Bottleneck callout
  let maxDrop = 0;
  let bottleneck = "";
  for (let i = 1; i < stages.length; i++) {
    const drop = stages[i].prev - stages[i].count;
    if (drop > maxDrop) { maxDrop = drop; bottleneck = stages[i].label; }
  }
  if (bottleneck && maxDrop > 0) {
    doc.rect(MARGIN, y, CONTENT_W, 36).fill(C.warnBg).stroke(C.warn);
    doc.fillColor(C.warn).font("Helvetica-Bold").fontSize(9)
       .text("⚠  Biggest Bottleneck", MARGIN + 10, y + 8);
    doc.fillColor(C.text).font("Helvetica").fontSize(9)
       .text(`${fmtNum(maxDrop)} leads dropped at the ${bottleneck} stage — the largest single conversion gap in your funnel.`, MARGIN + 10, y + 20, { width: CONTENT_W - 20 });
    y += 48;
  }

  // ────────────────────────────────────────────────────────────────────────────
  // PAGE 4: OUTREACH PERFORMANCE
  // ────────────────────────────────────────────────────────────────────────────
  newPage("Outreach Performance");

  y = BODY_TOP;
  y = drawSectionHeading(doc, "Key Metrics vs Benchmarks", y);
  y += 8;

  const metricsItems = [
    { label: "Open Rate",          value: data.metrics.openRate   !== null ? `${data.metrics.openRate}%`   : "—", note: "Target: 40-60%",   statusKey: "openRate",    rawValue: data.metrics.openRate   },
    { label: "Reply Rate",         value: data.metrics.replyRate  !== null ? `${data.metrics.replyRate}%`  : "—", note: "Target: 3-8%",    statusKey: "replyRate",   rawValue: data.metrics.replyRate  },
    { label: "Reply → Meeting",    value: data.metrics.meetingRate !== null ? `${data.metrics.meetingRate}%` : "—", note: "Target: >10%",   statusKey: "meetingRate", rawValue: data.metrics.meetingRate },
    { label: "Bounce Rate",        value: data.metrics.bounceRate !== null ? `${data.metrics.bounceRate}%` : "—", note: "Target: <2%",     statusKey: "bounceRate",  rawValue: data.metrics.bounceRate  },
    { label: "Unsubscribe Rate",   value: data.metrics.unsubRate  !== null ? `${data.metrics.unsubRate}%`  : "—", note: "Target: <0.5%",   statusKey: "unsubRate",   rawValue: data.metrics.unsubRate   },
    { label: "Emails Sent",        value: fmtNum(data.metrics.emailsSent), note: "Total across all tools" },
  ];

  y = drawMetricBoxes(doc, y, metricsItems, 3);
  y += 16;

  // Per-tool signal health table
  if (data.tools.length > 0) {
    y = drawSectionHeading(doc, "Per-Tool Signal Health", y);
    y += 8;

    const toolRows: RowData = data.tools.map((t) => {
      const statusMap: Record<string, string> = { healthy: "✓ Healthy", warning: "⚠ Warning", silent: "✗ Silent", never: "— No events" };
      const bgMap: Record<string, string> = { healthy: C.goodBg, warning: C.warnBg, silent: C.badBg, never: C.rowAlt };
      const colorMap: Record<string, string> = { healthy: C.good, warning: C.warn, silent: C.bad, never: C.subtext };
      return {
        cells: [t.label, t.channel, statusMap[t.status] ?? t.status, fmtNum(t.events24h), fmtNum(t.events7d)],
        bg: bgMap[t.status],
        textColor: colorMap[t.status],
      };
    });

    y = drawTable(doc, MARGIN, y, [
      { header: "Tool",      width: 150 },
      { header: "Channel",   width: 100 },
      { header: "Status",    width: 110 },
      { header: "Events 24h", width: 80, align: "right" },
      { header: "Events 7d",  width: 55, align: "right" },
    ], toolRows) + 20;
  }

  // ────────────────────────────────────────────────────────────────────────────
  // PAGE 5: SIGNAL ACTIVITY
  // ────────────────────────────────────────────────────────────────────────────
  newPage("Signal Activity");

  y = BODY_TOP;
  y = drawSectionHeading(doc, "Event Breakdown by Signal Tier", y);
  y += 8;

  const tierLabels: Record<number, string> = {
    1: "Tier 1 — High Intent",
    2: "Tier 2 — Warm Signals",
    3: "Tier 3 — Cold but Targeted",
    4: "Tier 4 — Experimental",
  };

  for (const tier of [1, 2, 3, 4]) {
    const group = data.signals.filter((s) => s.tier === tier);
    if (group.length === 0) continue;

    doc.fillColor(C.subtext).font("Helvetica-Bold").fontSize(8.5)
       .text(tierLabels[tier], MARGIN, y);
    y += 14;

    const tierRows: RowData = group.slice(0, 10).map((s) => ({
      cells: [s.event, fmtNum(s.count), `${Math.round((s.count / (data.signals.reduce((a, b) => a + b.count, 0) || 1)) * 100)}%`],
    }));

    y = drawTable(doc, MARGIN, y, [
      { header: "Event Type",   width: 280 },
      { header: "Count",        width: 120, align: "right" },
      { header: "% of Total",   width: 95,  align: "right" },
    ], tierRows, 20) + 12;
  }

  doc.end();
}
